[build]
  publish = "build/"

[functions]
  directory = "api/analytics"

[[redirects]]
  from = "/blog/:year/:month/:slug"
  to = "/:slug"
  status = 301

[[redirects]]
  from = "/posts/:slug"
  to = "/:slug"
  status = 301

[[redirects]]
  from = "/preso/:slug"
  to = "/:slug"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/"
  status = 301

[[redirects]]
  from = "/jquery/*"
  to = "/jquery?path=:splat"
  status = 301

[[redirects]]
  from = "/regex-101"
  to = "/regex"
  status = 301
